<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [15]:
import numpy as np

listado = [0,1,2,3,4,5,6,7,8,9]
array_unidimensional = np.array(listado)
print(array_unidimensional)

[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [16]:
array_bidimensional = np.reshape(array_unidimensional,(2,5)) ### toma el primer array y lo convierte en 2 x 5
array_bidimensional

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [17]:
a = np.array([0, 2, 0, 3, 0, 4, 0])

resultado_where = np.where(a != 0) ### busca el indice de la condicion que se cumple
print(f'Los índices son{resultado_where}')


Los índices son(array([1, 3, 5], dtype=int64),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [18]:
b = np.random.randint(0,2,(3,3)) ### numero de 0 a 1, en un tablero de 3 filas y 3 columnas
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [19]:
array_randint_tri = np.random.randint(0,10,10) ### coloco el punto de partida, el punto final, y cuantos numeros quiero
maximo = np.max(array_randint_tri)
minimo = np.min(array_randint_tri)

print(f'El minimo es {minimo}')
print(f'El maximo es {maximo}')

El minimo es 0
El maximo es 9


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [20]:
c = np.array([1,2,3,4,5,6])

c[::-1]

array([6, 5, 4, 3, 2, 1])


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [21]:
d = np.random.randint(1,25,(2,3,4))

In [22]:

where_15 = np.where(d == 15)
print(d)
print(where_15)


[[[ 7 11 21 20]
  [ 5  8 19  8]
  [ 5  7 21 16]]

 [[ 2  3  3  8]
  [20  6 15  7]
  [16  7  4 12]]]
(array([1], dtype=int64), array([1], dtype=int64), array([2], dtype=int64))


In [23]:
d[d==15][0]

15

In [24]:
d[0]

array([[ 7, 11, 21, 20],
       [ 5,  8, 19,  8],
       [ 5,  7, 21, 16]])

In [25]:
d[1,-1,:]

array([16,  7,  4, 12])


#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [26]:
e = np.random.randint(1,31,(3,2,5))
e

array([[[28, 15, 26, 27, 30],
        [25, 11, 10, 11, 29]],

       [[16, 17, 11, 25, 22],
        [14, 29, 22, 22, 28]],

       [[12, 14,  4, 17,  4],
        [22, 29, 23,  7, 29]]])

In [27]:
e[0,0:2,0:2]

array([[28, 15],
       [25, 11]])

In [28]:
e[1:3,1,:]

array([[14, 29, 22, 22, 28],
       [22, 29, 23,  7, 29]])

#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [29]:
f = np.random.randint(1,25,(4,3,2))
f

array([[[17, 19],
        [ 2, 10],
        [ 1, 24]],

       [[24, 17],
        [14, 18],
        [15, 23]],

       [[19, 12],
        [18, 10],
        [21,  9]],

       [[ 8, 11],
        [ 5,  1],
        [22, 21]]])

In [30]:
f[1,1,:] = 0
f[-1,:,:] = -1

f

array([[[17, 19],
        [ 2, 10],
        [ 1, 24]],

       [[24, 17],
        [ 0,  0],
        [15, 23]],

       [[19, 12],
        [18, 10],
        [21,  9]],

       [[-1, -1],
        [-1, -1],
        [-1, -1]]])


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [31]:
h = np.random.randint(-10,14,(2,4,3))
h

array([[[ -6,   3,   5],
        [ -7,  -6,  -1],
        [  6,   7,   4],
        [-10,   7,  -8]],

       [[  0,  -7,  10],
        [ -1,  -3,   1],
        [  0,   5,  12],
        [  5,   2,  -4]]])

In [32]:
h[h>5]

array([ 6,  7,  7, 10, 12])

In [33]:
h[h<0] = 0 ### busca los elementos del array 0, y sustituye esos numeros por 0. Además, actualiza el array
h

array([[[ 0,  3,  5],
        [ 0,  0,  0],
        [ 6,  7,  4],
        [ 0,  7,  0]],

       [[ 0,  0, 10],
        [ 0,  0,  1],
        [ 0,  5, 12],
        [ 5,  2,  0]]])

#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [34]:
trid= np.random.randint(1,28,(3,3,3))
trid

array([[[26, 15, 20],
        [ 8, 13, 16],
        [27,  1, 21]],

       [[22,  6, 22],
        [10, 21, 22],
        [ 3, 27, 24]],

       [[11,  2, 22],
        [19, 19,  1],
        [ 5, 12, 17]]])

In [35]:
trid[1,:,:2]

array([[22,  6],
       [10, 21],
       [ 3, 27]])

In [36]:
matriz_3 = trid[2]
matriz_3[matriz_3 >20]

array([22])

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [37]:
num_10 = np.random.randint(1,25,10)
num_10

array([ 6, 17,  8,  2, 17,  5,  9,  2,  7, 24])

In [38]:
### busca los indices
max_1 = np.max(num_10)
min_1 = np.min(num_10)

ubicacion_max_1 = np.where(num_10 == max_1)
ubicacion_min_1 = np.where(num_10 == min_1)
print('El máximo y el mínimo son', max_1, min_1)



El máximo y el mínimo son 24 2


In [39]:
num_10[ubicacion_max_1] = 0
num_10[ubicacion_min_1] = 0
print(f'\n Este es el array {num_10}')


 Este es el array [ 6 17  8  0 17  5  9  0  7  0]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [40]:
num_15 = np.random.randint(1,101,15)
num_15.sort()
num_15


array([ 6, 14, 26, 27, 28, 32, 35, 36, 41, 44, 47, 78, 82, 95, 99])

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [41]:
matriz_4x4 = np.random.randint(1,16,(4,4)) 
print(matriz_4x4)


suma_col = np.sum(matriz_4x4, axis = 0)
suma_filas = np.sum(matriz_4x4, axis =1)

print(f'La suma de las columnas es {suma_col} y la suma de las filas es {suma_filas}')

[[12 10  3  4]
 [ 3  9  2 12]
 [ 2  7 15  3]
 [ 9  5 13  7]]
La suma de las columnas es [26 31 33 26] y la suma de las filas es [29 26 27 34]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [42]:
### pensarlo
matriz_5x5 = np.zeros((5,5))
matriz_5x5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
matriz_5x5[0,:] = 1
matriz_5x5[4,:] = 1
matriz_5x5[:,0] = 1
matriz_5x5[:,4] = 1
matriz_5x5


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [44]:
numeros_ale10 = np.random.randint(1,25,10)
mean = np.mean(numeros_ale10)
std = np.std(numeros_ale10)
print(numeros_ale10)
print(f'La media es {mean} y la desviación estándar es {std}')

[ 9 20 22 18 14 22 14 20 18  9]
La media es 16.6 y la desviación estándar es 4.6303347611160905


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


*** El primer eje pasa a ser el último, pasamos de 2 a 4 matrices
*** El segundo eje queda igual, mantenemos 3 filas
*** El tercer eje pasa a ser el primer eje, cambiamos de 4 columnas a 2


In [45]:
m = np.random.randint(1,25,(2,3,4))

m

array([[[ 4,  5, 22, 14],
        [11,  9, 18, 21],
        [13,  1,  6, 14]],

       [[ 7, 21, 22, 16],
        [20, 16,  7, 20],
        [ 2, 15,  5, 23]]])

In [46]:
n = np.transpose(m,(2,1,0))

n

array([[[ 4,  7],
        [11, 20],
        [13,  2]],

       [[ 5, 21],
        [ 9, 16],
        [ 1, 15]],

       [[22, 22],
        [18,  7],
        [ 6,  5]],

       [[14, 16],
        [21, 20],
        [14, 23]]])

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [47]:
x = np.random.randint(1,25,(3,4,2))
x


array([[[ 5, 17],
        [ 4,  6],
        [ 6,  5],
        [24, 11]],

       [[ 4,  2],
        [14,  3],
        [19,  3],
        [22, 10]],

       [[13, 22],
        [ 5, 13],
        [ 3, 16],
        [19, 23]]])

In [48]:
y = np.transpose(x,(1,0,2))

y

array([[[ 5, 17],
        [ 4,  2],
        [13, 22]],

       [[ 4,  6],
        [14,  3],
        [ 5, 13]],

       [[ 6,  5],
        [19,  3],
        [ 3, 16]],

       [[24, 11],
        [22, 10],
        [19, 23]]])

#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [49]:
abba = np.random.randint(1,25,(3,2,4))
abba

array([[[19, 17,  4, 12],
        [13, 15, 10,  5]],

       [[21, 16,  5, 20],
        [20, 22, 10,  9]],

       [[19, 15, 22, 15],
        [ 7,  5,  5,  5]]])

In [50]:
bbaa = np.transpose(abba,(2,0,1))
bbaa

array([[[19, 13],
        [21, 20],
        [19,  7]],

       [[17, 15],
        [16, 22],
        [15,  5]],

       [[ 4, 10],
        [ 5, 10],
        [22,  5]],

       [[12,  5],
        [20,  9],
        [15,  5]]])

#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [51]:
manipulable_1 = np.random.randint(-10,11,(3,4,5))
manipulable_1

array([[[ -4,   0,   6,  -8,   5],
        [ -4,   4,   0,  10,   0],
        [ -1, -10,  -3,   7,  -8],
        [ -9, -10,   5,   8,  -1]],

       [[  6,  -5,  -2,  -1,   5],
        [  0,   5,  -4,   0,   8],
        [  5,  -8,   6,  -9,   8],
        [  8,  -8,  -3,   0,  -7]],

       [[  6,   9,  -5,  10, -10],
        [ -9,  -2,   6,   6,  -9],
        [  6,   9,   9,   2,  -3],
        [ -4,   9,  -1,   0,   8]]])

In [52]:
manipulable_vacio = np.empty((3,4,5), dtype='U100') 
manipulable_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U100')

In [53]:
m_max = np.max(manipulable_1)
m_min = np.min(manipulable_1)
m_median = np.median(manipulable_1)

print(f'El valor máximo es {m_max}, el valor mínimo es {m_min} y la mediana es {m_median}')

El valor máximo es 10, el valor mínimo es -10 y la mediana es 0.0


In [54]:
manipulable_1[manipulable_1 == m_median]

array([0, 0, 0, 0, 0, 0, 0])

In [55]:
manipulable_1[manipulable_1 > m_median]

array([ 6,  5,  4, 10,  7,  5,  8,  6,  5,  5,  8,  5,  6,  8,  8,  6,  9,
       10,  6,  6,  6,  9,  9,  2,  9,  8])

In [56]:
manipulable_1[manipulable_1 < m_median]

array([ -4,  -8,  -4,  -1, -10,  -3,  -8,  -9, -10,  -1,  -5,  -2,  -1,
        -4,  -8,  -9,  -8,  -3,  -7,  -5, -10,  -9,  -2,  -9,  -3,  -4,
        -1])

In [57]:
ubicacion_menores_mediana = np.where(manipulable_1 < m_median)
ubicacion_menores_mediana

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
        2, 2, 2, 2, 2], dtype=int64),
 array([0, 0, 1, 2, 2, 2, 2, 3, 3, 3, 0, 0, 0, 1, 2, 2, 3, 3, 3, 0, 0, 1,
        1, 1, 2, 3, 3], dtype=int64),
 array([0, 3, 0, 0, 1, 2, 4, 0, 1, 4, 1, 2, 3, 2, 1, 3, 1, 2, 4, 2, 4, 0,
        1, 4, 4, 0, 2], dtype=int64))

In [58]:
manipulable_vacio[ubicacion_menores_mediana] = 'Y'

manipulable_vacio

array([[['Y', '', '', 'Y', ''],
        ['Y', '', '', '', ''],
        ['Y', 'Y', 'Y', '', 'Y'],
        ['Y', 'Y', '', '', 'Y']],

       [['', 'Y', 'Y', 'Y', ''],
        ['', '', 'Y', '', ''],
        ['', 'Y', '', 'Y', ''],
        ['', 'Y', 'Y', '', 'Y']],

       [['', '', 'Y', '', 'Y'],
        ['Y', 'Y', '', '', 'Y'],
        ['', '', '', '', 'Y'],
        ['Y', '', 'Y', '', '']]], dtype='<U100')

In [59]:
ubicacion_mayores_mediana = np.where(manipulable_1 > m_median)
ubicacion_mayores_mediana

(array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2], dtype=int64),
 array([0, 0, 1, 1, 2, 3, 3, 0, 0, 1, 1, 2, 2, 2, 3, 0, 0, 0, 1, 1, 2, 2,
        2, 2, 3, 3], dtype=int64),
 array([2, 4, 1, 3, 3, 2, 3, 0, 4, 1, 4, 0, 2, 4, 0, 0, 1, 3, 2, 3, 0, 1,
        2, 3, 1, 4], dtype=int64))

In [60]:
manipulable_vacio[ubicacion_mayores_mediana] = 'X'

manipulable_vacio

array([[['Y', '', 'X', 'Y', 'X'],
        ['Y', 'X', '', 'X', ''],
        ['Y', 'Y', 'Y', 'X', 'Y'],
        ['Y', 'Y', 'X', 'X', 'Y']],

       [['X', 'Y', 'Y', 'Y', 'X'],
        ['', 'X', 'Y', '', 'X'],
        ['X', 'Y', 'X', 'Y', 'X'],
        ['X', 'Y', 'Y', '', 'Y']],

       [['X', 'X', 'Y', 'X', 'Y'],
        ['Y', 'Y', 'X', 'X', 'Y'],
        ['X', 'X', 'X', 'X', 'Y'],
        ['Y', 'X', 'Y', '', 'X']]], dtype='<U100')

In [61]:
ubicacion_mediana = np.where(manipulable_1 == m_median)
ubicacion_mediana

(array([0, 0, 0, 1, 1, 1, 2], dtype=int64),
 array([0, 1, 1, 1, 1, 3, 3], dtype=int64),
 array([1, 2, 4, 0, 3, 3, 3], dtype=int64))

In [62]:
manipulable_vacio[ubicacion_mediana] = 'M'
manipulable_vacio

array([[['Y', 'M', 'X', 'Y', 'X'],
        ['Y', 'X', 'M', 'X', 'M'],
        ['Y', 'Y', 'Y', 'X', 'Y'],
        ['Y', 'Y', 'X', 'X', 'Y']],

       [['X', 'Y', 'Y', 'Y', 'X'],
        ['M', 'X', 'Y', 'M', 'X'],
        ['X', 'Y', 'X', 'Y', 'X'],
        ['X', 'Y', 'Y', 'M', 'Y']],

       [['X', 'X', 'Y', 'X', 'Y'],
        ['Y', 'Y', 'X', 'X', 'Y'],
        ['X', 'X', 'X', 'X', 'Y'],
        ['Y', 'X', 'Y', 'M', 'X']]], dtype='<U100')

In [63]:
ubicacion_max = np.where(manipulable_1 == m_max)
ubicacion_max


(array([0, 2], dtype=int64),
 array([1, 0], dtype=int64),
 array([3, 3], dtype=int64))

In [64]:
manipulable_vacio[ubicacion_max] = 'max'

manipulable_vacio

array([[['Y', 'M', 'X', 'Y', 'X'],
        ['Y', 'X', 'M', 'max', 'M'],
        ['Y', 'Y', 'Y', 'X', 'Y'],
        ['Y', 'Y', 'X', 'X', 'Y']],

       [['X', 'Y', 'Y', 'Y', 'X'],
        ['M', 'X', 'Y', 'M', 'X'],
        ['X', 'Y', 'X', 'Y', 'X'],
        ['X', 'Y', 'Y', 'M', 'Y']],

       [['X', 'X', 'Y', 'max', 'Y'],
        ['Y', 'Y', 'X', 'X', 'Y'],
        ['X', 'X', 'X', 'X', 'Y'],
        ['Y', 'X', 'Y', 'M', 'X']]], dtype='<U100')

In [65]:
ubicacion_min = np.where(manipulable_1 == m_min)
ubicacion_min

(array([0, 0, 2], dtype=int64),
 array([2, 3, 0], dtype=int64),
 array([1, 1, 4], dtype=int64))

In [66]:
manipulable_vacio[ubicacion_min] = 'min'

manipulable_vacio

array([[['Y', 'M', 'X', 'Y', 'X'],
        ['Y', 'X', 'M', 'max', 'M'],
        ['Y', 'min', 'Y', 'X', 'Y'],
        ['Y', 'min', 'X', 'X', 'Y']],

       [['X', 'Y', 'Y', 'Y', 'X'],
        ['M', 'X', 'Y', 'M', 'X'],
        ['X', 'Y', 'X', 'Y', 'X'],
        ['X', 'Y', 'Y', 'M', 'Y']],

       [['X', 'X', 'Y', 'max', 'min'],
        ['Y', 'Y', 'X', 'X', 'Y'],
        ['X', 'X', 'X', 'X', 'Y'],
        ['Y', 'X', 'Y', 'M', 'X']]], dtype='<U100')

In [67]:
array = np.random.randint(-10,10, (3,4,5))
print(array)

array_vacio = np.empty((3,4,5), dtype = str)

print("\n")

median = np.median(array)
max = np.max(array)
min = np.min(array)

print(f"La mediana es {median} \n")

array_vacio[array == median] = "M"
array_vacio[array == max] = "MAX"
array_vacio[array == min] = "MIN"
array_vacio[array > median] = "X"
array_vacio[array < median] = "Y"

print(array_vacio)

[[[ -9  -4  -7   1   0]
  [  4   6   4  -5   8]
  [ -2 -10  -1 -10  -3]
  [  6   6  -9  -9  -5]]

 [[-10   4   7   2   0]
  [ -8  -8   5  -5  -6]
  [ -8   0   9   3   7]
  [  2  -9  -2   9  -3]]

 [[  3   1   0   9   5]
  [-10 -10   0   9   9]
  [  3  -9  -5   2  -8]
  [  7   9  -1  -8  -1]]]


La mediana es 0.0 

[[['Y' 'Y' 'Y' 'X' 'M']
  ['X' 'X' 'X' 'Y' 'X']
  ['Y' 'Y' 'Y' 'Y' 'Y']
  ['X' 'X' 'Y' 'Y' 'Y']]

 [['Y' 'X' 'X' 'X' 'M']
  ['Y' 'Y' 'X' 'Y' 'Y']
  ['Y' 'M' 'X' 'X' 'X']
  ['X' 'Y' 'Y' 'X' 'Y']]

 [['X' 'X' 'M' 'X' 'X']
  ['Y' 'Y' 'M' 'X' 'X']
  ['X' 'Y' 'Y' 'X' 'Y']
  ['X' 'X' 'Y' 'Y' 'Y']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [68]:
array_final = np.random.randint(-10,10, (4,4))
array_final

array([[ 0, -4, -9, -9],
       [ 8,  9, -6,  0],
       [ 5, -7, -2, -6],
       [-1,  8,  4,  9]])

In [69]:
array_final[0]

array([ 0, -4, -9, -9])

In [70]:
encontrado = False

for i in range(4):
    fila = list(array_final[i])
    
    # Recorremos las columnas
    for j in range(4):
        # Creamos una lista con los elementos de la columna j
        columna = [array_final[x][j] for x in range(4)]
        
        if fila == columna:
            print(f"La fila {i} es igual a la columna {j}")
            encontrado = True
            break
if not encontrado:
    print("No hay ninguna fila que coincida exactamente con alguna columna.")


No hay ninguna fila que coincida exactamente con alguna columna.
