<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [1]:
import numpy as np

listado = [0,1,2,3,4,5,6,7,8,9]
array_unidimensional = np.array(listado)
print(array_unidimensional)

[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [2]:
array_bidimensional = np.reshape(array_unidimensional,(2,5)) ### toma el primer array y lo convierte en 2 x 5
array_bidimensional

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [3]:
a = np.array([0, 2, 0, 3, 0, 4, 0])
a !=0

resultado_where = np.where(a != 0) ### busca el indice de la condicion que se cumple
print(f'Los índices son{resultado_where}')


Los índices son(array([1, 3, 5]),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [4]:
b = np.random.randint(0,1,(3,3)) ### numero de 0 a 1, en un tablero de 3 filas y 3 columnas
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [5]:
array_randint_tri = np.random.randint(0,10,10) ### coloco el punto de partida, el punto final, y cuantos numeros quiero
maximo = np.max(array_randint_tri)
minimo = np.min(array_randint_tri)

print(f'El minimo es {minimo}')
print(f'El maximo es {maximo}')

El minimo es 0
El maximo es 9


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [6]:
c = np.array([1,2,3,4,5,6])

c[::-1]

array([6, 5, 4, 3, 2, 1])


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [10]:
d = np.random.randint(1,24,(2,3,4))


In [11]:

where_15 = np.where(d == 15)
print(d)
print(where_15)


[[[ 1  9 21 17]
  [17  4 20 19]
  [ 5 14 17  3]]

 [[22 13 13 15]
  [14 17  8  9]
  [13 10 10  8]]]
(array([1]), array([0]), array([3]))


In [12]:
d[d==15][0]

np.int32(15)

In [61]:
d[0]

array([[ 3, 22, 19, 11],
       [ 3,  2,  8,  1],
       [11, 18, 15, 23]], dtype=int32)

In [73]:
d[1,-1,:]

array([15,  2, 11, 14], dtype=int32)


#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [64]:
e = np.random.randint(1,30,(3,2,5))


array([[[23,  3, 27, 20, 12],
        [ 7, 13, 28, 11, 26]],

       [[17, 26, 19, 20, 24],
        [23, 12,  9, 13,  1]],

       [[26, 16,  5,  5, 13],
        [21, 14,  1,  8, 15]]], dtype=int32)

In [72]:
e[0,0:2,0:2]


array([[23,  3],
       [ 7, 13]], dtype=int32)

In [75]:
e[1:3,1,:]

array([[23, 12,  9, 13,  1],
       [21, 14,  1,  8, 15]], dtype=int32)

#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [81]:
f = np.random.randint(1,24,(4,3,2))
f

array([[[10, 10],
        [10,  5],
        [15,  4]],

       [[12,  5],
        [ 2,  4],
        [17,  6]],

       [[ 9,  2],
        [15,  3],
        [16, 20]],

       [[ 7,  7],
        [16,  8],
        [ 4,  1]]], dtype=int32)

In [92]:
f[1,1,:] = 0
f[-1,:,:] = -1

f

array([[[10, 10],
        [10,  5],
        [15,  4]],

       [[12,  5],
        [ 0,  0],
        [17,  6]],

       [[ 9,  2],
        [15,  3],
        [16, 20]],

       [[-1, -1],
        [-1, -1],
        [-1, -1]]], dtype=int32)


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [101]:
h = np.random.randint(-10,13,(2,4,3))
h

array([[[ -9,   1,   5],
        [  6,   2,   0],
        [  9,  -4,  -5],
        [  7,  -9,  -1]],

       [[  8,   4,   1],
        [ 10,   6,   1],
        [  5,   2,  -4],
        [-10, -10,  12]]], dtype=int32)

In [102]:
h[h>5]

array([ 6,  9,  7,  8, 10,  6, 12], dtype=int32)

In [112]:
h[h<0] = 0 ### busca los elementos del array 0, y sustituye esos numeros por 0. Además, actualiza el array
h

array([[[ 0,  1,  5],
        [ 6,  2,  0],
        [ 9,  0,  0],
        [ 7,  0,  0]],

       [[ 8,  4,  1],
        [10,  6,  1],
        [ 5,  2,  0],
        [ 0,  0, 12]]], dtype=int32)

#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [13]:
trid= np.random.randint(1,27,(3,3,3))
trid

array([[[21,  9, 25],
        [23,  2,  1],
        [19,  6, 11]],

       [[12, 15,  7],
        [25, 21, 19],
        [ 1, 20,  7]],

       [[25,  3, 11],
        [ 6,  3, 23],
        [ 8, 16, 24]]], dtype=int32)

In [14]:
trid[1,:,:2]

array([[12, 15],
       [25, 21],
       [ 1, 20]], dtype=int32)

In [15]:
matriz_3 = trid[2]
matriz_3[matriz_3 >20]

array([25, 23, 24], dtype=int32)

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [26]:
num_10 = np.random.randint(1,25,10)
num_10

array([ 7, 18,  1, 21, 13, 24, 19, 13,  2,  5], dtype=int32)

In [33]:
### busca los indices

max_1 = np.max(num_10)
min_1 = np.min(num_10)
ordenada = np.sort(num_10)
print('El máximo y el mínimo son', max_1, min_1)

print(ordenada)
ordenada[0] = 0
ordenada[-1] = 0

print(ordenada)

ordenada = num_10


El máximo y el mínimo son 24 1
[ 1  2  5  7 13 13 18 19 21 24]
[ 0  2  5  7 13 13 18 19 21  0]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [35]:
num_15 = np.random.randint(1,100,15)
num_15.sort()
num_15


array([10, 12, 21, 22, 23, 38, 39, 41, 46, 56, 76, 83, 89, 94, 95],
      dtype=int32)

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [38]:
matriz_4x4 = np.random.randint(1,16,(4,4)) 
print(matriz_4x4)


suma_col = np.sum(matriz_4x4, axis = 0)
suma_filas = np.sum(matriz_4x4, axis =1)

print(f'La suma de las columnas es {suma_col} y la suma de las filas es {suma_filas}')

[[11 13  3  2]
 [ 8 15  2  3]
 [ 1  1  5 11]
 [ 5  7  1 11]]
La suma de las columnas es [25 36 11 27] y la suma de las filas es [29 28 18 24]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [52]:
### pensarlo
matriz_5x5 = np.zeros((5,5))
matriz_5x5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
matriz_5x5[0,:] = 1
matriz_5x5[4,:] = 1
matriz_5x5[:,0] = 1
matriz_5x5[:,4] = 1
matriz_5x5


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [45]:
numeros_ale10 = np.random.randint(1,25,10)
mean = np.mean(numeros_ale10)
std = np.std(numeros_ale10)
print(numeros_ale10)
print(f'La media es {mean} y la desviación estándar es {std}')

[17  8 21 11  2  1 18  3 24 18]
La media es 12.3 y la desviación estándar es 8.000624975587845


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


### explicar

In [59]:
m = np.random.randint(1,24,(2,3,4))

m

array([[[15, 13, 20,  9],
        [ 5,  2, 15, 15],
        [17,  5, 16,  3]],

       [[23, 22,  6, 18],
        [ 7, 18,  7, 19],
        [ 9, 10,  5, 10]]], dtype=int32)

In [61]:
n = np.transpose(m,(2,1,0))

n

array([[[15, 23],
        [ 5,  7],
        [17,  9]],

       [[13, 22],
        [ 2, 18],
        [ 5, 10]],

       [[20,  6],
        [15,  7],
        [16,  5]],

       [[ 9, 18],
        [15, 19],
        [ 3, 10]]], dtype=int32)

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [62]:
x = np.random.randint(1,24,(3,4,2))
x


array([[[ 5, 21],
        [15, 20],
        [22,  8],
        [21, 18]],

       [[ 9, 10],
        [21, 15],
        [19, 13],
        [13, 11]],

       [[ 4,  1],
        [18, 15],
        [15, 13],
        [15, 17]]], dtype=int32)

In [65]:
y = np.transpose(x,(1,0,2))

y

array([[[ 5, 21],
        [ 9, 10],
        [ 4,  1]],

       [[15, 20],
        [21, 15],
        [18, 15]],

       [[22,  8],
        [19, 13],
        [15, 13]],

       [[21, 18],
        [13, 11],
        [15, 17]]], dtype=int32)

#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [68]:
abba = np.random.randint(1,24,(3,2,4))
abba

array([[[13,  6,  2, 20],
        [ 1,  4,  1, 21]],

       [[ 4,  9, 21, 20],
        [ 9, 18,  9, 16]],

       [[ 2,  5, 15, 23],
        [ 9,  6, 20,  3]]], dtype=int32)

In [70]:
bbaa = np.transpose(abba,(2,0,1))
bbaa

array([[[13,  1],
        [ 4,  9],
        [ 2,  9]],

       [[ 6,  4],
        [ 9, 18],
        [ 5,  6]],

       [[ 2,  1],
        [21,  9],
        [15, 20]],

       [[20, 21],
        [20, 16],
        [23,  3]]], dtype=int32)

#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [73]:
manipulable_1 = np.random.randint(-10,10,(3,4,5))
manipulable_1

array([[[ -3,   1,   4,  -8,  -3],
        [ -3,   0,   7,   1,   4],
        [  1,  -1, -10,   3,  -8],
        [  8,   1,   1,   2,   4]],

       [[ -1,  -3,  -5,   3,   6],
        [-10,  -7,  -5,  -1,   8],
        [ -4,  -9,  -7,   2,  -4],
        [ -8,  -6,   4,   6,  -7]],

       [[ -4,  -1,   4,  -7,  -4],
        [ -6,  -6,  -7, -10, -10],
        [  4,   9,  -3,  -7,  -2],
        [  7,  -1,   9,  -1,  -2]]], dtype=int32)

In [82]:
manipulable_vacio = np.empty((3,4,5), dtype=str) 
manipulable_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [83]:
m_max = np.max(manipulable_1)
m_min = np.min(manipulable_1)
m_median = np.median(manipulable_1)

print(f'El valor máximo es {m_max}, el valor mínimo es {m_min} y la mediana es {m_median}')

El valor máximo es 9, el valor mínimo es -10 y la mediana es -1.5


In [84]:
manipulable_1[manipulable_1 == m_median]

array([], dtype=int32)

In [85]:
manipulable_1[manipulable_1 > m_median]

array([ 1,  4,  0,  7,  1,  4,  1, -1,  3,  8,  1,  1,  2,  4, -1,  3,  6,
       -1,  8,  2,  4,  6, -1,  4,  4,  9,  7, -1,  9, -1], dtype=int32)

In [86]:
manipulable_1[manipulable_1 < m_median]

array([ -3,  -8,  -3,  -3, -10,  -8,  -3,  -5, -10,  -7,  -5,  -4,  -9,
        -7,  -4,  -8,  -6,  -7,  -4,  -7,  -4,  -6,  -6,  -7, -10, -10,
        -3,  -7,  -2,  -2], dtype=int32)

In [91]:
ubicacion_menores_mediana = np.where(manipulable_1 < m_median)
ubicacion_menores_mediana

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 0, 0, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 0, 0, 0, 1,
        1, 1, 1, 1, 2, 2, 2, 3]),
 array([0, 3, 4, 0, 2, 4, 1, 2, 0, 1, 2, 0, 1, 2, 4, 0, 1, 4, 0, 3, 4, 0,
        1, 2, 3, 4, 2, 3, 4, 4]))

In [92]:
manipulable_vacio[ubicacion_menores_mediana] = 'Y'

manipulable_vacio

array([[['Y', '', '', 'Y', 'Y'],
        ['Y', '', '', '', ''],
        ['', '', 'Y', '', 'Y'],
        ['', '', '', '', '']],

       [['', 'Y', 'Y', '', ''],
        ['Y', 'Y', 'Y', '', ''],
        ['Y', 'Y', 'Y', '', 'Y'],
        ['Y', 'Y', '', '', 'Y']],

       [['Y', '', '', 'Y', 'Y'],
        ['Y', 'Y', 'Y', 'Y', 'Y'],
        ['', '', 'Y', 'Y', 'Y'],
        ['', '', '', '', 'Y']]], dtype='<U1')

In [93]:
ubicacion_mayores_mediana = np.where(manipulable_1 > m_median)
ubicacion_mayores_mediana

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 0, 0, 0, 1, 1, 2, 3, 3,
        0, 0, 2, 2, 3, 3, 3, 3]),
 array([1, 2, 1, 2, 3, 4, 0, 1, 3, 0, 1, 2, 3, 4, 0, 3, 4, 3, 4, 3, 2, 3,
        1, 2, 0, 1, 0, 1, 2, 3]))

In [94]:
manipulable_vacio[ubicacion_mayores_mediana] = 'X'

manipulable_vacio

array([[['Y', 'X', 'X', 'Y', 'Y'],
        ['Y', 'X', 'X', 'X', 'X'],
        ['X', 'X', 'Y', 'X', 'Y'],
        ['X', 'X', 'X', 'X', 'X']],

       [['X', 'Y', 'Y', 'X', 'X'],
        ['Y', 'Y', 'Y', 'X', 'X'],
        ['Y', 'Y', 'Y', 'X', 'Y'],
        ['Y', 'Y', 'X', 'X', 'Y']],

       [['Y', 'X', 'X', 'Y', 'Y'],
        ['Y', 'Y', 'Y', 'Y', 'Y'],
        ['X', 'X', 'Y', 'Y', 'Y'],
        ['X', 'X', 'X', 'X', 'Y']]], dtype='<U1')

In [95]:
ubicacion_mediana = np.where(manipulable_1 == m_median)
ubicacion_mediana

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

In [97]:
manipulable_vacio[ubicacion_mediana] = 'M'
manipulable_vacio

array([[['Y', 'X', 'X', 'Y', 'Y'],
        ['Y', 'X', 'X', 'X', 'X'],
        ['X', 'X', 'Y', 'X', 'Y'],
        ['X', 'X', 'X', 'X', 'X']],

       [['X', 'Y', 'Y', 'X', 'X'],
        ['Y', 'Y', 'Y', 'X', 'X'],
        ['Y', 'Y', 'Y', 'X', 'Y'],
        ['Y', 'Y', 'X', 'X', 'Y']],

       [['Y', 'X', 'X', 'Y', 'Y'],
        ['Y', 'Y', 'Y', 'Y', 'Y'],
        ['X', 'X', 'Y', 'Y', 'Y'],
        ['X', 'X', 'X', 'X', 'Y']]], dtype='<U1')

In [99]:
ubicacion_max = np.where(manipulable_1 == m_max)
ubicacion_max


(array([2, 2]), array([2, 3]), array([1, 2]))

In [100]:
manipulable_vacio[ubicacion_max] = 'max'

manipulable_vacio

array([[['Y', 'X', 'X', 'Y', 'Y'],
        ['Y', 'X', 'X', 'X', 'X'],
        ['X', 'X', 'Y', 'X', 'Y'],
        ['X', 'X', 'X', 'X', 'X']],

       [['X', 'Y', 'Y', 'X', 'X'],
        ['Y', 'Y', 'Y', 'X', 'X'],
        ['Y', 'Y', 'Y', 'X', 'Y'],
        ['Y', 'Y', 'X', 'X', 'Y']],

       [['Y', 'X', 'X', 'Y', 'Y'],
        ['Y', 'Y', 'Y', 'Y', 'Y'],
        ['X', 'm', 'Y', 'Y', 'Y'],
        ['X', 'X', 'm', 'X', 'Y']]], dtype='<U1')

In [101]:
ubicacion_min = np.where(manipulable_1 == m_min)
ubicacion_min

(array([0, 1, 2, 2]), array([2, 1, 1, 1]), array([2, 0, 3, 4]))

In [102]:
manipulable_vacio[ubicacion_min] = 'b'

manipulable_vacio

array([[['Y', 'X', 'X', 'Y', 'Y'],
        ['Y', 'X', 'X', 'X', 'X'],
        ['X', 'X', 'b', 'X', 'Y'],
        ['X', 'X', 'X', 'X', 'X']],

       [['X', 'Y', 'Y', 'X', 'X'],
        ['b', 'Y', 'Y', 'X', 'X'],
        ['Y', 'Y', 'Y', 'X', 'Y'],
        ['Y', 'Y', 'X', 'X', 'Y']],

       [['Y', 'X', 'X', 'Y', 'Y'],
        ['Y', 'Y', 'Y', 'b', 'b'],
        ['X', 'm', 'Y', 'Y', 'Y'],
        ['X', 'X', 'm', 'X', 'Y']]], dtype='<U1')

#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.