<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [3]:
import numpy as np

listado = [0,1,2,3,4,5,6,7,8,9]
array_unidimensional = np.array(listado)
print(array_unidimensional)

[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [4]:
array_bidimensional = np.reshape(array_unidimensional,(2,5)) ### toma el primer array y lo convierte en 2 x 5
array_bidimensional

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [5]:
a = np.array([0, 2, 0, 3, 0, 4, 0])
a !=0

resultado_where = np.where(a != 0) ### busca el indice de la condicion que se cumple
print(f'Los índices son{resultado_where}')


Los índices son(array([1, 3, 5]),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [6]:
b = np.random.randint(0,1,(3,3)) ### numero de 0 a 1, en un tablero de 3 filas y 3 columnas
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [7]:
array_randint_tri = np.random.randint(0,10,10) ### coloco el punto de partida, el punto final, y cuantos numeros quiero
maximo = np.max(array_randint_tri)
minimo = np.min(array_randint_tri)

print(f'El minimo es {minimo}')
print(f'El maximo es {maximo}')

El minimo es 0
El maximo es 9


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [8]:
c = np.array([1,2,3,4,5,6])

c[::-1]

array([6, 5, 4, 3, 2, 1])


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [14]:
d = np.random.randint(1,24,(2,3,4))


In [15]:

where_15 = np.where(d == 15)
print(d)
print(where_15)


[[[12 17  9 15]
  [ 7 10  8  9]
  [ 5 20 17  7]]

 [[23 14  6 14]
  [ 1  6 11 14]
  [10  4 10 22]]]
(array([0]), array([0]), array([3]))


In [16]:
d[d==15][0]

np.int32(15)

In [17]:
d[0]

array([[12, 17,  9, 15],
       [ 7, 10,  8,  9],
       [ 5, 20, 17,  7]], dtype=int32)

In [18]:
d[1,-1,:]

array([10,  4, 10, 22], dtype=int32)


#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [21]:
e = np.random.randint(1,30,(3,2,5))
e

array([[[14, 17, 29, 19,  8],
        [25, 19, 13, 14, 15]],

       [[11, 21, 24, 13,  4],
        [28, 19, 19, 12,  9]],

       [[29, 15, 14, 20,  2],
        [ 1,  3, 20, 14, 24]]], dtype=int32)

In [20]:
e[0,0:2,0:2]


array([[21, 25],
       [26, 19]], dtype=int32)

In [22]:
e[1:3,1,:]

array([[28, 19, 19, 12,  9],
       [ 1,  3, 20, 14, 24]], dtype=int32)

#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [81]:
f = np.random.randint(1,24,(4,3,2))
f

array([[[10, 10],
        [10,  5],
        [15,  4]],

       [[12,  5],
        [ 2,  4],
        [17,  6]],

       [[ 9,  2],
        [15,  3],
        [16, 20]],

       [[ 7,  7],
        [16,  8],
        [ 4,  1]]], dtype=int32)

In [92]:
f[1,1,:] = 0
f[-1,:,:] = -1

f

array([[[10, 10],
        [10,  5],
        [15,  4]],

       [[12,  5],
        [ 0,  0],
        [17,  6]],

       [[ 9,  2],
        [15,  3],
        [16, 20]],

       [[-1, -1],
        [-1, -1],
        [-1, -1]]], dtype=int32)


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [101]:
h = np.random.randint(-10,13,(2,4,3))
h

array([[[ -9,   1,   5],
        [  6,   2,   0],
        [  9,  -4,  -5],
        [  7,  -9,  -1]],

       [[  8,   4,   1],
        [ 10,   6,   1],
        [  5,   2,  -4],
        [-10, -10,  12]]], dtype=int32)

In [102]:
h[h>5]

array([ 6,  9,  7,  8, 10,  6, 12], dtype=int32)

In [112]:
h[h<0] = 0 ### busca los elementos del array 0, y sustituye esos numeros por 0. Además, actualiza el array
h

array([[[ 0,  1,  5],
        [ 6,  2,  0],
        [ 9,  0,  0],
        [ 7,  0,  0]],

       [[ 8,  4,  1],
        [10,  6,  1],
        [ 5,  2,  0],
        [ 0,  0, 12]]], dtype=int32)

#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [13]:
trid= np.random.randint(1,27,(3,3,3))
trid

array([[[21,  9, 25],
        [23,  2,  1],
        [19,  6, 11]],

       [[12, 15,  7],
        [25, 21, 19],
        [ 1, 20,  7]],

       [[25,  3, 11],
        [ 6,  3, 23],
        [ 8, 16, 24]]], dtype=int32)

In [14]:
trid[1,:,:2]

array([[12, 15],
       [25, 21],
       [ 1, 20]], dtype=int32)

In [15]:
matriz_3 = trid[2]
matriz_3[matriz_3 >20]

array([25, 23, 24], dtype=int32)

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [36]:
num_10 = np.random.randint(1,25,10)
num_10

array([ 8, 15, 17,  2, 14, 19,  7,  3,  8, 23], dtype=int32)

In [41]:
### busca los indices
max_1 = np.max(num_10)
min_1 = np.min(num_10)

ubicacion_max_1 = np.where(num_10 == max_1)
ubicacion_min_1 = np.where(num_10 == min_1)
print('El máximo y el mínimo son', max_1, min_1)



El máximo y el mínimo son 23 2


In [42]:
num_10[ubicacion_max_1] = 0
num_10[ubicacion_min_1] = 0
print(f'\n Este es el array {num_10}')


 Este es el array [ 8 15 17  0 14 19  7  3  8  0]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [35]:
num_15 = np.random.randint(1,100,15)
num_15.sort()
num_15


array([10, 12, 21, 22, 23, 38, 39, 41, 46, 56, 76, 83, 89, 94, 95],
      dtype=int32)

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [38]:
matriz_4x4 = np.random.randint(1,16,(4,4)) 
print(matriz_4x4)


suma_col = np.sum(matriz_4x4, axis = 0)
suma_filas = np.sum(matriz_4x4, axis =1)

print(f'La suma de las columnas es {suma_col} y la suma de las filas es {suma_filas}')

[[11 13  3  2]
 [ 8 15  2  3]
 [ 1  1  5 11]
 [ 5  7  1 11]]
La suma de las columnas es [25 36 11 27] y la suma de las filas es [29 28 18 24]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [52]:
### pensarlo
matriz_5x5 = np.zeros((5,5))
matriz_5x5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
matriz_5x5[0,:] = 1
matriz_5x5[4,:] = 1
matriz_5x5[:,0] = 1
matriz_5x5[:,4] = 1
matriz_5x5


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [45]:
numeros_ale10 = np.random.randint(1,25,10)
mean = np.mean(numeros_ale10)
std = np.std(numeros_ale10)
print(numeros_ale10)
print(f'La media es {mean} y la desviación estándar es {std}')

[17  8 21 11  2  1 18  3 24 18]
La media es 12.3 y la desviación estándar es 8.000624975587845


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


*** El primer eje pasa a ser el último, pasamos de 2 a 4 matrices
*** El segundo eje queda igual, mantenemos 3 filas
*** El tercer eje pasa a ser el primer eje, cambiamos de 4 columnas a 2


In [43]:
m = np.random.randint(1,24,(2,3,4))

m

array([[[ 8,  3, 10, 12],
        [ 8, 14,  2, 16],
        [ 1,  2,  5,  4]],

       [[18, 21,  2, 21],
        [14,  3, 17,  9],
        [16, 10, 23, 17]]], dtype=int32)

In [44]:
n = np.transpose(m,(2,1,0))

n

array([[[ 8, 18],
        [ 8, 14],
        [ 1, 16]],

       [[ 3, 21],
        [14,  3],
        [ 2, 10]],

       [[10,  2],
        [ 2, 17],
        [ 5, 23]],

       [[12, 21],
        [16,  9],
        [ 4, 17]]], dtype=int32)

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [45]:
x = np.random.randint(1,24,(3,4,2))
x


array([[[10, 14],
        [ 4,  6],
        [ 8,  2],
        [ 5, 21]],

       [[10,  1],
        [10, 13],
        [15, 20],
        [ 9, 22]],

       [[ 3, 17],
        [ 8,  5],
        [ 4, 15],
        [19, 22]]], dtype=int32)

In [46]:
y = np.transpose(x,(1,0,2))

y

array([[[10, 14],
        [10,  1],
        [ 3, 17]],

       [[ 4,  6],
        [10, 13],
        [ 8,  5]],

       [[ 8,  2],
        [15, 20],
        [ 4, 15]],

       [[ 5, 21],
        [ 9, 22],
        [19, 22]]], dtype=int32)

#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [47]:
abba = np.random.randint(1,24,(3,2,4))
abba

array([[[ 4,  6,  5,  2],
        [ 5,  2,  5, 12]],

       [[ 5, 17, 14,  7],
        [ 7,  9, 10, 12]],

       [[ 5, 14,  1, 15],
        [ 9,  1, 14, 10]]], dtype=int32)

In [48]:
bbaa = np.transpose(abba,(2,0,1))
bbaa

array([[[ 4,  5],
        [ 5,  7],
        [ 5,  9]],

       [[ 6,  2],
        [17,  9],
        [14,  1]],

       [[ 5,  5],
        [14, 10],
        [ 1, 14]],

       [[ 2, 12],
        [ 7, 12],
        [15, 10]]], dtype=int32)

#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [49]:
manipulable_1 = np.random.randint(-10,10,(3,4,5))
manipulable_1

array([[[ -7,  -9,  -4,  -2,   3],
        [ -1,   1,   0,  -8,  -1],
        [  3,   5,   5,   9, -10],
        [  7,  -6,   8,  -7,   2]],

       [[  4,  -3,  -1,   8,   2],
        [ -3,   9,  -2,   7,   2],
        [ -4,   7,   7,  -4,  -1],
        [  7,   5,  -5,   7,   1]],

       [[ -2,  -3,  -9,   8,  -2],
        [  1,   8,   2,   5,  -1],
        [  1,   6,   6,   7,  -8],
        [  6,  -9,  -1,   7,  -3]]], dtype=int32)

In [50]:
manipulable_vacio = np.empty((3,4,5), dtype='U100') 
manipulable_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U100')

In [51]:
m_max = np.max(manipulable_1)
m_min = np.min(manipulable_1)
m_median = np.median(manipulable_1)

print(f'El valor máximo es {m_max}, el valor mínimo es {m_min} y la mediana es {m_median}')

El valor máximo es 9, el valor mínimo es -10 y la mediana es 1.0


In [52]:
manipulable_1[manipulable_1 == m_median]

array([1, 1, 1, 1], dtype=int32)

In [53]:
manipulable_1[manipulable_1 > m_median]

array([3, 3, 5, 5, 9, 7, 8, 2, 4, 8, 2, 9, 7, 2, 7, 7, 7, 5, 7, 8, 8, 2,
       5, 6, 6, 7, 6, 7], dtype=int32)

In [54]:
manipulable_1[manipulable_1 < m_median]

array([ -7,  -9,  -4,  -2,  -1,   0,  -8,  -1, -10,  -6,  -7,  -3,  -1,
        -3,  -2,  -4,  -4,  -1,  -5,  -2,  -3,  -9,  -2,  -1,  -8,  -9,
        -1,  -3], dtype=int32)

In [55]:
ubicacion_menores_mediana = np.where(manipulable_1 < m_median)
ubicacion_menores_mediana

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
        2, 2, 2, 2, 2, 2]),
 array([0, 0, 0, 0, 1, 1, 1, 1, 2, 3, 3, 0, 0, 1, 1, 2, 2, 2, 3, 0, 0, 0,
        0, 1, 2, 3, 3, 3]),
 array([0, 1, 2, 3, 0, 2, 3, 4, 4, 1, 3, 1, 2, 0, 2, 0, 3, 4, 2, 0, 1, 2,
        4, 4, 4, 1, 2, 4]))

In [56]:
manipulable_vacio[ubicacion_menores_mediana] = 'Y'

manipulable_vacio

array([[['Y', 'Y', 'Y', 'Y', ''],
        ['Y', '', 'Y', 'Y', 'Y'],
        ['', '', '', '', 'Y'],
        ['', 'Y', '', 'Y', '']],

       [['', 'Y', 'Y', '', ''],
        ['Y', '', 'Y', '', ''],
        ['Y', '', '', 'Y', 'Y'],
        ['', '', 'Y', '', '']],

       [['Y', 'Y', 'Y', '', 'Y'],
        ['', '', '', '', 'Y'],
        ['', '', '', '', 'Y'],
        ['', 'Y', 'Y', '', 'Y']]], dtype='<U100')

In [57]:
ubicacion_mayores_mediana = np.where(manipulable_1 > m_median)
ubicacion_mayores_mediana

(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
        2, 2, 2, 2, 2, 2]),
 array([0, 2, 2, 2, 2, 3, 3, 3, 0, 0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 0, 1, 1,
        1, 2, 2, 2, 3, 3]),
 array([4, 0, 1, 2, 3, 0, 2, 4, 0, 3, 4, 1, 3, 4, 1, 2, 0, 1, 3, 3, 1, 2,
        3, 1, 2, 3, 0, 3]))

In [58]:
manipulable_vacio[ubicacion_mayores_mediana] = 'X'

manipulable_vacio

array([[['Y', 'Y', 'Y', 'Y', 'X'],
        ['Y', '', 'Y', 'Y', 'Y'],
        ['X', 'X', 'X', 'X', 'Y'],
        ['X', 'Y', 'X', 'Y', 'X']],

       [['X', 'Y', 'Y', 'X', 'X'],
        ['Y', 'X', 'Y', 'X', 'X'],
        ['Y', 'X', 'X', 'Y', 'Y'],
        ['X', 'X', 'Y', 'X', '']],

       [['Y', 'Y', 'Y', 'X', 'Y'],
        ['', 'X', 'X', 'X', 'Y'],
        ['', 'X', 'X', 'X', 'Y'],
        ['X', 'Y', 'Y', 'X', 'Y']]], dtype='<U100')

In [59]:
ubicacion_mediana = np.where(manipulable_1 == m_median)
ubicacion_mediana

(array([0, 1, 2, 2]), array([1, 3, 1, 2]), array([1, 4, 0, 0]))

In [60]:
manipulable_vacio[ubicacion_mediana] = 'M'
manipulable_vacio

array([[['Y', 'Y', 'Y', 'Y', 'X'],
        ['Y', 'M', 'Y', 'Y', 'Y'],
        ['X', 'X', 'X', 'X', 'Y'],
        ['X', 'Y', 'X', 'Y', 'X']],

       [['X', 'Y', 'Y', 'X', 'X'],
        ['Y', 'X', 'Y', 'X', 'X'],
        ['Y', 'X', 'X', 'Y', 'Y'],
        ['X', 'X', 'Y', 'X', 'M']],

       [['Y', 'Y', 'Y', 'X', 'Y'],
        ['M', 'X', 'X', 'X', 'Y'],
        ['M', 'X', 'X', 'X', 'Y'],
        ['X', 'Y', 'Y', 'X', 'Y']]], dtype='<U100')

In [61]:
ubicacion_max = np.where(manipulable_1 == m_max)
ubicacion_max


(array([0, 1]), array([2, 1]), array([3, 1]))

In [62]:
manipulable_vacio[ubicacion_max] = 'max'

manipulable_vacio

array([[['Y', 'Y', 'Y', 'Y', 'X'],
        ['Y', 'M', 'Y', 'Y', 'Y'],
        ['X', 'X', 'X', 'max', 'Y'],
        ['X', 'Y', 'X', 'Y', 'X']],

       [['X', 'Y', 'Y', 'X', 'X'],
        ['Y', 'max', 'Y', 'X', 'X'],
        ['Y', 'X', 'X', 'Y', 'Y'],
        ['X', 'X', 'Y', 'X', 'M']],

       [['Y', 'Y', 'Y', 'X', 'Y'],
        ['M', 'X', 'X', 'X', 'Y'],
        ['M', 'X', 'X', 'X', 'Y'],
        ['X', 'Y', 'Y', 'X', 'Y']]], dtype='<U100')

In [63]:
ubicacion_min = np.where(manipulable_1 == m_min)
ubicacion_min

(array([0]), array([2]), array([4]))

In [64]:
manipulable_vacio[ubicacion_min] = 'min'

manipulable_vacio

array([[['Y', 'Y', 'Y', 'Y', 'X'],
        ['Y', 'M', 'Y', 'Y', 'Y'],
        ['X', 'X', 'X', 'max', 'min'],
        ['X', 'Y', 'X', 'Y', 'X']],

       [['X', 'Y', 'Y', 'X', 'X'],
        ['Y', 'max', 'Y', 'X', 'X'],
        ['Y', 'X', 'X', 'Y', 'Y'],
        ['X', 'X', 'Y', 'X', 'M']],

       [['Y', 'Y', 'Y', 'X', 'Y'],
        ['M', 'X', 'X', 'X', 'Y'],
        ['M', 'X', 'X', 'X', 'Y'],
        ['X', 'Y', 'Y', 'X', 'Y']]], dtype='<U100')

In [65]:
array = np.random.randint(-10,10, (3,4,5))
print(array)

array_vacio = np.empty((3,4,5), dtype = str)

print("\n")

median = np.median(array)
max = np.max(array)
min = np.min(array)

print(f"La mediana es {median} \n")

array_vacio[array == median] = "M"
array_vacio[array == max] = "MAX"
array_vacio[array == min] = "MIN"
array_vacio[array > median] = "X"
array_vacio[array < median] = "Y"

print(array_vacio)

[[[  3  -1   1  -4   2]
  [ -3  -2   6   9  -3]
  [  8  -8  -9  -8   0]
  [  6  -5   7   2  -8]]

 [[  2   9   3 -10   3]
  [ -7  -5  -1   4  -5]
  [  1   3  -8  -3   2]
  [ -1  -5  -3   7  -3]]

 [[-10  -7  -4  -1  -7]
  [ -3  -3   9   1   5]
  [  9  -4  -2   6   2]
  [  5   3  -8   9   7]]]


La mediana es -1.0 

[[['X' 'M' 'X' 'Y' 'X']
  ['Y' 'Y' 'X' 'X' 'Y']
  ['X' 'Y' 'Y' 'Y' 'X']
  ['X' 'Y' 'X' 'X' 'Y']]

 [['X' 'X' 'X' 'Y' 'X']
  ['Y' 'Y' 'M' 'X' 'Y']
  ['X' 'X' 'Y' 'Y' 'X']
  ['M' 'Y' 'Y' 'X' 'Y']]

 [['Y' 'Y' 'Y' 'M' 'Y']
  ['Y' 'Y' 'X' 'X' 'X']
  ['X' 'Y' 'Y' 'X' 'X']
  ['X' 'X' 'Y' 'X' 'X']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [66]:
array_final = np.random.randint(-10,10, (4,4))
array_final

array([[  2,  -1,   8,  -9],
       [ -9,   0,  -4,  -3],
       [  2,  -8,  -8,  -8],
       [ -9,  -8,   5, -10]], dtype=int32)

In [67]:
array_final[0]

array([ 2, -1,  8, -9], dtype=int32)

In [68]:
encontrado = False

for i in range(4):
    fila = list(array_final[i])
    
    # Recorremos las columnas
    for j in range(4):
        # Creamos una lista con los elementos de la columna j
        columna = [array_final[x][j] for x in range(4)]
        
        if fila == columna:
            print(f"La fila {i} es igual a la columna {j}")
            encontrado = True
            break
if not encontrado:
    print("No hay ninguna fila que coincida exactamente con alguna columna.")


No hay ninguna fila que coincida exactamente con alguna columna.
